### ISSUE TITLE
[BLOG POST] Terminal-tips

### ISSUE THREAD

**Issue by AkshathaLaxmi** [pesos/pesos.github.io#13]
# Title:

Revival of terminal-tips

# Abstract:

I feel like it might be a great idea to restart contribution towards tips and tricks about the terminal that people know, to share with everyone who're interested in exploring more about it.

**Comment by Gituser143** [comment]
I'm in, sounds good !!!

**Comment by tfidfwastaken** [comment]
This is a nice idea.

We used to have a repository back a few years back where the community shared some nice tips, which I archived due to inactivity.

This would work great as a blog post that has been contributed by multiple people in the community.

I'll wait for a few more people to pitch in here, after which I'll explain how you can start writing the post.

**Comment by metonymic-smokey** [comment]
I'm in too!
Would the club also be open to handy tricks with git in the terminal or maybe even small useful bash scripts(this one is only after we have a sizeable collection of other tips and tricks)?

**Comment by MadhavJivrajani** [comment]
Amazing idea! Let's do it! Can't wait to learn, thanks!

**Comment by AshishShenoy** [comment]
I'm down as well, got some decent input for this.

**Comment by RAMYA-CP** [comment]
I'm in too!!!

**Comment by shivansh8** [comment]
its a great idea!! im in !!

**Comment by akhil-eppa** [comment]
A great idea!! It will be a great way to strengthen one's fundamentals. I'm in.

**Comment by tfidfwastaken** [comment]
I'm assigning you all to contribute to this. We'll plan on how we materialise this into an actual blog post.

So I thought the format of the blog post could be something like:

### [Title for the tip]
*Contributed by: [your name and github handle]*
[description about what your tip does with accompanying code snippet]

--- 

### [Title for the next tip]
*Contributed by: [your name and github handle]*
[description about what your tip does with accompanying code snippet]

--- 
...and so on

**Comment by tfidfwastaken** [comment]
I will create the markdown file for this post tomorrow.
The workflow should be familiar to all of you by now.
All you have to do is add your tip/tips in markdown format and send the pull request.
The file you have to change will be in the `_posts` folder. I'll tell you its name when I make it.
### But there is one change to note. Do not send your PR to the master branch!
I'll make a separate branch which you have to send a PR to. Maybe I'll call it something like `terminal-tips-branch`.

**Comment by tfidfwastaken** [comment]
Okay, I have opened a new branch called `terminal-tips` and created the file in `_posts/`.

You can now start sending in your Pull Requests for the same. If you have any questions, ask them over here!

**Remember to work only on the `terminal-tips` branch, not `master`!**

**Comment by tfidfwastaken** [comment]
Hey hey hey assignees
Where are your tips

**Comment by akhil-eppa** [comment]
I have started noting them down. I will add them very soon

**Comment by AkshathaLaxmi** [comment]
Hey! I'm a little confused about the format of the tips. Is there no explanation for the tip?

**Comment by AkshathaLaxmi** [comment]
Also I'm a little dumb and did not check the dropdown under branch *hides under a rock*

**Comment by metonymic-smokey** [comment]
@alastairmoody-madeye I think an explanation is required, going by the format:
" description about what your tip does with accompanying code snippet."

**Comment by tfidfwastaken** [comment]
@alastairmoody-madeye I see your PR, and it looks great!

We all are still learning and you are definitely not dumb for not immediately getting this stuff, it isn't that obvious at all!
