### ISSUE TITLE
Bug: Getting Started Page Links related

### ISSUE THREAD

**Issue by VishalUdupi** [pesos/pesos.github.io#15]
The Getting Started page has an bug where the Take -Me -To Links (Text Part) is getting trimmed off. These are the links present in the right upper half part of the website under the getting started tab of the website. Small preview of it is shown below :
![Screenshot (6)_LI](https://user-images.githubusercontent.com/47077925/64192670-de36e080-ce98-11e9-9dc2-5a4ad0aebf1b.jpg)

**Comment by tfidfwastaken** [comment]
Yes. Thanks for opening an issue here.
The issue might be fixed by changing some CSS property.
Someone can try experimenting with Inspect Element in the browser.

**Comment by Samyak2** [comment]
![image](https://user-images.githubusercontent.com/34161949/64338569-c6c63780-cfff-11e9-81c2-f2bebc06f6a6.png)
I experimented using Inspect Element and found that adding "white-space: pre-wrap;" CSS tag to the anchor tag worked well (as seen in the above image). Should I send a PR with the required changes?

**Comment by VishalUdupi** [comment]
That's great! also could u try to do the same for the remaining sections in getting started tab of the website? like this was just a single section of the webpage ie: in the  about part only, the rest of the subsections also need this adjustment. these can be accessed from the left hand side of the webpage when you open the getting started page.

**Comment by Samyak2** [comment]
The same CSS tag works for all the links.
`a {
    white-space: pre-wrap;
}`
But I was not able to find the CSS or HTML files to add them...

**Comment by VishalUdupi** [comment]
Yeah I do know that , even I faced some issues while locating the CSS files.

**Comment by tfidfwastaken** [comment]
@Samyak2 
@techie0007 
Yeah, you won't find the css files because the way the website works is that we have a bunch of sass files which compile to CSS when jekyll is generating the website. 

You might have to add your css to `_sass/custom.scss` 
Based on playing around with the inspector, my guess would be to add a line like:
```css
ul.toc .toc-h2, ul.toc .toc-h2 a, ul.toc .toc-h3, ul.toc .toc-h3 a, ul.toc .toc-h4, ul.toc .toc-h4 a, ul.toc .toc-h5, ul.toc .toc-h5 a, ul.toc .toc-h6, ul.toc .toc-h6 a {
    white-space: pre-wrap;
}
```
Try adding that and seeing if that works. But you are definitely in the right direction with the css property needed to be used. Seems to be doing what we want.

Also if you open a PR, make sure it is a PR to the `development` branch, not `master`.

**Comment by tfidfwastaken** [comment]
Who wants to be assigned to this?

**Comment by Samyak2** [comment]
I'll try to do it. How do I run/test the website to check if it's working?

**Comment by VishalUdupi** [comment]
Even I'll try to do it , I'll let u know if I get it

**Comment by Samyak2** [comment]
I managed to get the Jekyll site running on my laptop after installing/uninstalling lots of packages. Adding the CSS for the anchor tag in `_sass/custom.scss` worked as you suggested @tfidfwastaken. I'll send a PR now.

**Comment by tfidfwastaken** [comment]
I guess I'll just merge the pull now, since there has been no further discussion here.
I'll confirm if it worked fine locally for me.

**Comment by tfidfwastaken** [comment]
Works great!
The changes will be reflected on our website soon.
Thanks for helping out!

**Comment by Samyak2** [comment]
That's great!
Happy to help
