### ISSUE TITLE
[BLOG POST] How Linux made me a better developer

### ISSUE THREAD

**Issue by anihm136** [pesos/pesos.github.io#33]
# Title:
How Linux made me a better developer

# Abstract:
When a Linux user says that Linux is best for developers, it is often unclear to other non-linux users what improvements and benefits it offers over other OS's, specially when they have all the tooling set up and find it hard to migrate. This post aims to describe, objectively, what improvements I experienced as a programmer after making the switch

**Comment by tfidfwastaken** [comment]
Great and clear abstract! 
Let's make this happen!

**Comment by tfidfwastaken** [comment]
Any progress on this?

**Comment by anihm136** [comment]
Sorry, been a bit busy lately. I'll get it done this week
