### ISSUE TITLE
[BLOG POST] Ricing introduction

### ISSUE THREAD

**Issue by psiayn** [pesos/pesos.github.io#39]
# Title: What in the world is _ricing_ !?

# Abstract: 
The term _ricing_ is something that maybe most Linux users have come across while browsing the depths of the internet. This post will clear up the air around ricing, such as _"What is it?"_  and _"Why do I need it?"_. It will help people to get their hands dirty with ricing and maybe make their stay at Linux more exciting!

**Comment by tfidfwastaken** [comment]
I really like this idea.
I just want a clarification. Is this post more about the culture/community around ricing, or a guide to get started with ricing?

Personally I find the former more exciting, as that would stand out a little better than a lot of easily available ricing guides. The fact that you want to address "Why do I need it" makes it seem like you are on the same boat as me.

For me the special sauce for a post like this is if you can dig up more information and history of the term "ricing" and give just a little more info and insight than what you would find on r/unixporn.

I am imagining my ideal to be something like:
- Start with introducing ricing as an analogy like "car mods but for desktops"
- Ricing like car modding, can be of all kinds: some extend functionality, some are purely form over function, some are intentionally hilarious and ridiculous etc.
- How old is this practice? Where and when did it start getting popular?
- Is "ricing" actually a term with racist origins like some suggest? If yes, what are the implications of that being the prevalent term in this community? 
- Which software appears to be the "main pillars of ricing"? Who are the people/what's the story behind them?
- Give a shout out to some ricers you appreciate

Obviously these are purely my opinions/suggestions, all power to you to write your post however you want.

So yes please go ahead, I approve!

**Comment by psiayn** [comment]
It's kinda a mix of the culture of ricing and a quick start guide, rather than a plain old rice tutorial. Most of your ideals are kinda what I had in mind , sorry for not making that clear. I'm thinking of adding a rough path that one would follow if they'd like to rather than a complete detail as someone might be comfortable with something like Ubuntu rather than Pop. Thanks for the approval. 
I'll try to get it done in a few days.

**Comment by psiayn** [comment]
Hey I'm almost done. How do I upload/embed images into the file? I can't seem to find where to store the images/

**Comment by tfidfwastaken** [comment]
The images go in `assets/images`. Alternatively you can upload it to a third party like imgur and link that url too. 

Also don't forget to add author details in `data/authors.yml`, like [this](https://tianqi.name/jekyll-TeXt-theme/docs/en/authors). 

Also use the front matter in the same way as the previous posts to ensure that you are credited for it properly.
