### ISSUE TITLE
[BLOG POST] Delving into Docker

### ISSUE THREAD

**Issue by metonymic-smokey** [pesos/pesos.github.io#4]
# Title:
Delving into Docker : Part 1

# Abstract:
This will be the first of a 2 part series to familiarise PESOS members with Docker.
The first part will 
- briefly talk about containerisation and how container-based apps can be deployed.

- guide the members through a basic step-by-step tutorial to pull images from either DockerHub/GCR, basics of Dockerfiles, create and run instances of the images(i.e. docker containers) and a few other basics of woking with containers.

The next part will tie in these basics with the basics of creating a basic app, containerising basic apps and running them, using curl commands to obtain output, pushing the app images to DockerHub, etc. and generally explore Docker functionalities in-depth based on member interest in the same.

**Comment by tfidfwastaken** [comment]
Hi, currently we are not using this page to plan out workshops. We haven't confirmed any workshop yet. Make sure the blog post works out as an independent entity. Do edit the abstract accordingly.

**Comment by metonymic-smokey** [comment]
Hi, considered the same and edited the abstract. Thanks.

**Comment by Gituser143** [comment]
@metonymic-smokey any plans to implement this? I'd love to help too...

**Comment by metonymic-smokey** [comment]
@Gituser143 I'm open to writing for the PESOS blog.   
I'll get a rough draft outline of the topics and we'll discuss?

**Comment by Gituser143** [comment]
@metonymic-smokey, sounds good. Let's do it

**Comment by tfidfwastaken** [comment]
Anything came of this? @metonymic-smokey @Gituser143 
It might be worth looking into simplifying this to a single post exploring a single aspect I suppose?

**Comment by Gituser143** [comment]
We did start off, but we got occupied with other things I guess. :P 
We'll get this done asap.
