### ISSUE TITLE
Wrong use of terminal tip.

### ISSUE THREAD

**Issue by Gituser143** [pesos/pesos.github.io#40]
![image](https://user-images.githubusercontent.com/44526455/86962051-e11cf480-c17f-11ea-87a7-33a57e9e7c57.png)
@alastairmoody-madeye `!.` Doesn't necessarily run `./a.out`. It just executes the last command which started with the character placed after `!`, in this case, `.`  

It is in no way a shortcut to ./a.out  

A clearer example would be:

Last command starting with the letter "c": `cd ~/Documents`  
Now when you execute `!c`, it executes `cd ~/Documents`, which was the last command which started with the character after `!`...

**Comment by Gituser143** [comment]
Also, why does this keep repeatedly assign me?! @tfidfwastaken HALP

**Comment by tfidfwastaken** [comment]
Ooh that's subtle. Good catch. Shall assign @alastairmoody-madeye, but anyone else may feel free to correct this.

**Comment by AkshathaLaxmi** [comment]
Ohhh cool. I'll correct that. Thanks for pointing it out!
