### ISSUE TITLE
[BLOG POST] Building Android kernels

### ISSUE THREAD

**Issue by CaelestisZ** [pesos/pesos.github.io#42]
# Title:
Building Android kernels

# Abstract:
It's often told that flashing custom ROMs like the LineageOS (formerly known as Cyanogenmod), ResurrectionRemix, etc., can improve your Android experience. However, there is a misconception that these ROMs are the ones that greatly impact the performance and battery life of an Android device. 
That is not always the case, leaving aside the hardware limitations of the device, it is the kernel that is responsible for increased performance gains and enhanced battery life! Literally everything we do on our device involves the kernel. 

This post aims to explain what exactly an Android kernel is, why we should consider installing a custom Android kernel and also features a section to build an Android kernel from source.

**Comment by tfidfwastaken** [comment]
Awesome idea! Please go ahead and make this post happen.

If you have any questions about the process, you can always ask at the Slack channel :)
