### ISSUE TITLE
[BLOG POST] 0.1 + 0.2 is not equal to 0.3

### ISSUE THREAD

**Issue by tfidfwastaken** [pesos/pesos.github.io#47]
# Title: 0.1 + 0.2 and other fantastic ways to make money disappear
# Abstract:
Type `0.1 + 0.2 == 0.3` into the Python interpreter. Yep. It's false. Before you throw away Python, try it out in C. And C++. Also Java, Go, Rust, Julia or Assembly.

Let's explore why this bug in all languages that can never be "fixed", and how we go around it to make sure stock markets don't collapse and your weapons of mass destruction don't hit the wrong place.

## Who is your target audience with this post? Be as specific as you can.
All programmers who have to concern themselves with floating point calculations. This is some important stuff that nobody taught us which is a big sad.

**Comment by tfidfwastaken** [comment]
Assigning @anihm136 and @Gituser143 for comments and approval. :p

**Comment by Gituser143** [comment]
@tfidfwastaken you've got me curious about how you plan to get a blog post outta this! I'm not sure what you've got planned, but I want to see it. Make it happen fast fast, thanks xD

**Comment by anihm136** [comment]
Looks very exciting! Eagerly awaiting the post

**Comment by Gituser143** [comment]
Also, @tfidfwastaken, this isn't really the case in Go. You might want to look into that. [Here's](https://play.golang.org/p/WyjZz9qoqL8) a link which let's you try this out online (It's called the Go Playground).

**Comment by tfidfwastaken** [comment]
@Gituser143 
It's actually there in Go as well, just masked a little better. That said my title was a little inaccurate for Go's case
[Put those numbers in variables](https://play.golang.org/p/5Y1UGL8t45A) and it still happens. 

The reason for that will indirectly be explained in my post as well :)
