### ISSUE TITLE
Bug: Sharing link for any webpage broken on mobile website

### ISSUE THREAD

**Issue by AkshathaLaxmi** [pesos/pesos.github.io#56]
**Description**

Link for sharing on phone website produces a link that leads to a 404 error. 

**Steps to Reproduce**

1. Open any page from the website on your phone
2. Try and share the link by using the `share` button 
3. Open the link that you got from sharing
4. 404 error :/

**Expected behavior**

One should get the same link when they copy or use the share button.

**Links you get**

If you share it - https://pesos.pes.edu/2020/07/22/01-plus-02-is-not-03.html  [Broken]

If you copy the link - https://pesos.github.io/2020/07/22/01-plus-02-is-not-03.html [Not broken]

**Environment**

- OS: Android 10 (OnePlus 7)
- Browser: Chrome (Mobile)

**Comment by tfidfwastaken** [comment]
Fixed by https://github.com/pesos/pesos.github.io/commit/f178189992bec62ecc86e0d90e231672c300974c.
