### ISSUE TITLE
Bug: Incorrect Page Redirection in Blog

### ISSUE THREAD

**Issue by Sahith02** [pesos/pesos.github.io#57]
**Description**

In the blog section, when you go to page 2 and then try to go back to page 1 by clicking on the `1` button in the pagination component, it goes back to the home page. 

**Steps to Reproduce**

1. Open the website on the desktop version (haven't tried on the mobile version).
2. Head over to the blog page.
3. Go to page 2.
4. Try to go back to page 1 from the bottom pagination component.
5. Goes back to the home page.

**Expected behavior**

Should go back to page 1.

**Environment**

- Browser: Tried on only chrome desktop.

**Comment by tfidfwastaken** [comment]
Fixed by https://github.com/pesos/pesos.github.io/commit/f3a96bffae6ffe927b5dc1431ecdfd186f788b2b

Thanks for reporting!
