### ISSUE TITLE
Bug: GitHub organisation link broken in communication channels

### ISSUE THREAD

**Issue by Samyak2** [pesos/pesos.github.io#62]
**Description**

In the [communication channels page](https://pesos.github.io/get-started/communication-channels), the GitHub organisation link points to the same page. From the source, it can be seen that the link is empty.

**Expected behavior**

The link should point to: ```https://github.com/pesos```

**Screenshots (If Necessary)**

https://github.com/pesos/pesos.github.io/blame/master/get-started/3.1-communication-channels.md#L21

**Comment by suhaskv1** [comment]
I can do this, can I be assigned?
